# Generated by Django 5.1.5 on 2025-01-31 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_recipe_category_alter_recipe_cover'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='preparations_steps',
            new_name='preparation_steps',
        ),
    ]
