# Generated by Django 5.1.5 on 2025-01-31 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_rename_preparations_steps_recipe_preparation_steps'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='preparations_steps_is_html',
            new_name='preparation_steps_is_html',
        ),
    ]
